### ISSUE TITLE
Webook URL Validation

### ISSUE THREAD

**Issue by ncko** [Ironikus/wp-webhooks#1]
With WP Webhooks, I am experiencing a similar problem to this one: https://github.com/woocommerce/woocommerce/issues/9751

**Comment by Ironikus** [comment]
Hey, thanks for mentioning that! 
Did you try it with the temporary fix they provided within the other issue? 
You can also set the argument only for the wp_safe_remote_request function of WP Webhooks (and Pro) as follows: 

```
add_filter( 'wpwhpro/admin/webhooks/webhook_http_args', function( $args ) {
    $args['reject_unsafe_urls'] = false;

    return $args;
}, 10, 1);
```

Alternatively you can pass two more arguments: **$args** (which returns the parsed arguments) and **$url** (Which parses the URL the webhook gets sent to).

Hope this helps!

**Comment by ncko** [comment]
I did and it worked. Thank you so much.
