### ISSUE TITLE
Send Data On Post Update -> Media/Attachment Not Working

### ISSUE THREAD

**Issue by stevesearer** [Ironikus/wp-webhooks#2]
Just upgraded to the pro version of the plugin and was able to get it to work well for all post types except `attachment` and I found that by adding `attachment_updated` hook in addition to the existing `post_updated` hook I was able to get it to work on attachment updates:

`add_action( 'attachment_updated', array( $this, 'ironikus_trigger_post_update_init' ), 10, 3 );`

**Comment by Ironikus** [comment]
Hi @stevesearer - thank you a lot for your input, it's highly appreciated! I will take care that we include a fix for that with our next version launch. 
If you have any further questions in the meantime, feel free to reach out at any time!

**Comment by jannis24** [comment]
Hey @stevesearer - I just wanted to let you know that we fixed the issue with the latest update. If you have further questions, please let me know.
