### ISSUE TITLE
[BUG] Scheduled posts not being sent on publish

### ISSUE THREAD

**Issue by IOAyman** [Ironikus/wp-webhooks#6]
### Current behavior
I've setup a new `post_update` trigger to send post data when it gets published (screenshot bellow).  
When I publish a new post, or **manually** change its status to "Published" (i.e `publish`) from the UI, this trigger does send data. However, if I schedule a new post to be published sometime later, nothing is sent at all when it gets published.

![Screenshot 2022-04-11 at 10-39-53 WP Webhooks](https://user-images.githubusercontent.com/6185849/162711699-385d0ad7-e690-4110-8b4b-b33552c0896a.png)

### Expected behavior
When a scheduled post is actually published, the `post_update` trigger should actually detect that and send data.

--- 

```
WP version: 5.9.3
WP Webhooks version: 3.3.1
```

**Comment by Ironikus** [comment]
Hi @IOAyman - Simply uncheck "User must be logged in". WordPress uses Scheduled Tasks to update future published posts, so no user is involved.

**Comment by IOAyman** [comment]
Hi @Ironikus, thank you! That did it.
Good day ahead.
